import ToastProvider from "@/components/toastProvider/ToastProvider";
import Footer from "@/layouts/footer/Footer";
import Header from "@/layouts/header/Header";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
        <ToastProvider />
      </body>
    </html>
  );
}
